name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: npm install

    - name: Install Surge and gatsby
      run: npm install -g surge gatsby
      
    - name: Build Gatsby
      run: |
        cd ./site
        gatsby build

    - name: Deploy to Surge
      run:  surge ./public http://creamcityscene.com/ --token ${{secrets.SURGE_TOKEN}}
      
